/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * Editor.java
 *
 * Created on 2010-11-25, 22:06:30
 */
package Interface;

import java.awt.BorderLayout;

import javax.swing.BorderFactory;
import javax.swing.border.TitledBorder;

/**
 * 
 * @author Dorota
 */
public class Editor extends javax.swing.JPanel
{
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    public void initComponents( int width, int height )
    {
        _editorTextArea = new java.awt.TextArea();
        this.setSize( width, height );
        BorderLayout layout = new BorderLayout();
        this.setLayout( layout );
        this.add( _editorTextArea, BorderLayout.CENTER );
        createTitledBorder();
    }

    private void createTitledBorder()
    {
        TitledBorder title = BorderFactory.createTitledBorder( "Building editor" );
        this.setBorder( title );
    }

    // Variables declaration - do not modify
    private java.awt.TextArea _editorTextArea;
    // End of variables declaration
}
