/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * Editor.java
 *
 * Created on 2010-11-25, 22:06:30
 */
package Interface;

import java.awt.BorderLayout;

/**
 * 
 * @author Dorota
 */
public class Editor extends javax.swing.JPanel
{
    /** Creates new form Editor */
    // public Editor( int width, int height )
    // {
    // _width = width;
    // _height = height;
    // initComponents();
    // // _editorTextArea.setSize( width, height );
    // System.out.println( _editorTextArea.getSize() );
    // System.out.println( this.getWidth() );
    // }
    public Editor()
    {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents( int width, int height )
    {
        _editorTextArea = new java.awt.TextArea();
        this.setSize( width, height );
        BorderLayout layout = new BorderLayout();
        this.setLayout( layout );
        this.add( _editorTextArea, BorderLayout.CENTER );
    }// </editor-fold>

    // Variables declaration - do not modify
    private java.awt.TextArea _editorTextArea;
    // End of variables declaration
}
