/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * Main.java
 *
 * Created on 2010-11-13, 09:16:23
 */
package Interface;

import java.awt.BorderLayout;
import java.awt.Frame;

import javax.media.j3d.Canvas3D;

import com.sun.j3d.utils.universe.SimpleUniverse;

/**
 * 
 * @author Dorota
 */
public class Main extends javax.swing.JFrame
{
    /** Creates new form Main */
    public Main()
    {
        init();
    }

    private void init()
    {
        // setUndecorated( true ); //full screen
        initComponents();
        initCanvas();
        pack();
    }

    private void initCanvas()
    {
        _canvas = new Canvas3D( SimpleUniverse.getPreferredConfiguration() );
        _canvas.setDoubleBufferEnable( true );
        canvasPanel.setLayout( new BorderLayout() );
        canvasPanel.add( _canvas );
        _scene = new Scene3D( _canvas );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {
        menuPanel = new javax.swing.JPanel();
        blaLabel = new javax.swing.JLabel();
        canvasPanel = new javax.swing.JPanel();
        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );
        blaLabel.setText( "bla" );
        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout( menuPanel );
        menuPanel.setLayout( menuPanelLayout );
        menuPanelLayout.setHorizontalGroup( menuPanelLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            menuPanelLayout.createSequentialGroup().addGap( 32, 32, 32 ).addComponent( blaLabel,
                javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE )
                    .addContainerGap( 123, Short.MAX_VALUE ) ) );
        menuPanelLayout.setVerticalGroup( menuPanelLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            menuPanelLayout.createSequentialGroup().addGap( 36, 36, 36 ).addComponent( blaLabel,
                javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE )
                    .addContainerGap( 647, Short.MAX_VALUE ) ) );
        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout( canvasPanel );
        canvasPanel.setLayout( canvasPanelLayout );
        canvasPanelLayout.setHorizontalGroup( canvasPanelLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 770, Short.MAX_VALUE ) );
        canvasPanelLayout.setVerticalGroup( canvasPanelLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 723, Short.MAX_VALUE ) );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap().addComponent( canvasPanel,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE ).addGap( 18, 18, 18 ).addComponent( menuPanel,
                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE ) ) );
        layout.setVerticalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addComponent( menuPanel,
            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
            Short.MAX_VALUE ).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap().addComponent( canvasPanel,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE ) ) );
        pack();
    }// </editor-fold>

    /**
     * @param args
     *            the command line arguments
     */
    public static void main( String args[] )
    {
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                Main mainWindow = new Main();
                mainWindow.setExtendedState( Frame.MAXIMIZED_BOTH );
                mainWindow.setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel blaLabel;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration
    private Canvas3D _canvas;
    private Scene3D _scene;
}
