package Interface;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * MenuPanel.java
 *
 * Created on 2010-11-27, 10:44:40
 */
/**
 * 
 * @author Dorota
 */
public class MenuPanel extends javax.swing.JPanel
{
    /** Creates new form MenuPanel */
    public MenuPanel( Scene3D scene )
    {
        _editedScene = scene;
        // createTitle
        // setBackgroundColor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        _menuPanel = new javax.swing.JTabbedPane();
        _simulationTab = new javax.swing.JPanel();
        _simulationStopButton = new javax.swing.JButton();
        _simulationRestartButton = new javax.swing.JButton();
        _simulationContinueButton = new javax.swing.JButton();
        _simulationPauseButton = new javax.swing.JButton();
        _simulationStartButton = new javax.swing.JButton();
        _addingNewBlocksTab = new javax.swing.JPanel();
        _materialLabel = new javax.swing.JLabel();
        _newBlockLabel = new javax.swing.JLabel();
        _materialComboBox = new javax.swing.JComboBox();
        _blockCoordinatesLabel = new javax.swing.JLabel();
        _xCoordinateLabel = new javax.swing.JLabel();
        _yCoordinateLabel = new javax.swing.JLabel();
        _zCoordinateLabel = new javax.swing.JLabel();
        _xCoordinateTextField = new javax.swing.JTextField();
        _yCoordinateTextField = new javax.swing.JTextField();
        _zCoordinateTextField = new javax.swing.JTextField();
        _blockSizeLabel = new javax.swing.JLabel();
        _zSizeLabel = new javax.swing.JLabel();
        _zSizeTextField = new javax.swing.JTextField();
        _ySizeLabel = new javax.swing.JLabel();
        _ySizeTextField = new javax.swing.JTextField();
        _xSizeLabel = new javax.swing.JLabel();
        _xSizeTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JToggleButton();
        _helpTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _helpTextArea = new javax.swing.JTextArea();
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout( jPanel1 );
        jPanel1.setLayout( jPanel1Layout );
        jPanel1Layout.setHorizontalGroup( jPanel1Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        jPanel1Layout.setVerticalGroup( jPanel1Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout( jPanel2 );
        jPanel2.setLayout( jPanel2Layout );
        jPanel2Layout.setHorizontalGroup( jPanel2Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        jPanel2Layout.setVerticalGroup( jPanel2Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout( jPanel3 );
        jPanel3.setLayout( jPanel3Layout );
        jPanel3Layout.setHorizontalGroup( jPanel3Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        jPanel3Layout.setVerticalGroup( jPanel3Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        _simulationStopButton.setText( "Stop" );
        _simulationStopButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationStopButtonActionPerformed( evt );
            }
        } );
        _simulationRestartButton.setText( "Restart" );
        _simulationRestartButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationRestartButtonActionPerformed( evt );
            }
        } );
        _simulationContinueButton.setText( "Continue" );
        _simulationContinueButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationContinueButtonActionPerformed( evt );
            }
        } );
        _simulationPauseButton.setText( "Pause" );
        _simulationPauseButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationPauseButtonActionPerformed( evt );
            }
        } );
        _simulationStartButton.setText( "Start" );
        _simulationStartButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationStartButtonActionPerformed( evt );
            }
        } );
        javax.swing.GroupLayout _simulationTabLayout = new javax.swing.GroupLayout( _simulationTab );
        _simulationTab.setLayout( _simulationTabLayout );
        _simulationTabLayout.setHorizontalGroup( _simulationTabLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            _simulationTabLayout.createSequentialGroup().addContainerGap().addGroup(
                _simulationTabLayout
                        .createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addComponent( _simulationStopButton,
                            javax.swing.GroupLayout.Alignment.TRAILING,
                            javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE )
                        .addComponent( _simulationRestartButton,
                            javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE )
                        .addComponent( _simulationContinueButton,
                            javax.swing.GroupLayout.Alignment.TRAILING,
                            javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE )
                        .addComponent( _simulationPauseButton,
                            javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE )
                        .addComponent( _simulationStartButton,
                            javax.swing.GroupLayout.Alignment.TRAILING,
                            javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE ) ).addGap(
                183, 183, 183 ) ) );
        _simulationTabLayout.setVerticalGroup( _simulationTabLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            _simulationTabLayout.createSequentialGroup().addGap( 31, 31, 31 ).addComponent(
                _simulationStartButton ).addGap( 18, 18, 18 ).addComponent( _simulationStopButton )
                    .addGap( 18, 18, 18 ).addComponent( _simulationPauseButton )
                    .addGap( 18, 18, 18 ).addComponent( _simulationContinueButton ).addGap( 18, 18,
                        18 ).addComponent( _simulationRestartButton ).addContainerGap( 352,
                        Short.MAX_VALUE ) ) );
        _menuPanel.addTab( "Simulation", _simulationTab );
        _materialLabel.setText( "Material:" );
        _newBlockLabel.setText( "Add new block:" );
        _materialComboBox.setModel( new javax.swing.DefaultComboBoxModel( new String[]{ "Wood",
                "Air", "Metal", "Brick" } ) );
        _materialComboBox.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _materialComboBoxActionPerformed( evt );
            }
        } );
        _blockCoordinatesLabel.setText( "Block left-front-bottom coordinates:" );
        _xCoordinateLabel.setText( "x:" );
        _yCoordinateLabel.setText( "y:" );
        _zCoordinateLabel.setText( "z:" );
        _xCoordinateTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _xCoordinateTextFieldActionPerformed( evt );
            }
        } );
        _yCoordinateTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _yCoordinateTextFieldActionPerformed( evt );
            }
        } );
        _zCoordinateTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _zCoordinateTextFieldActionPerformed( evt );
            }
        } );
        _blockSizeLabel.setText( "Block size:" );
        _zSizeLabel.setText( "z:" );
        _zSizeTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _zSizeTextFieldActionPerformed( evt );
            }
        } );
        _ySizeLabel.setText( "y:" );
        _ySizeTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _ySizeTextFieldActionPerformed( evt );
            }
        } );
        _xSizeLabel.setText( "x:" );
        _xSizeTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _xSizeTextFieldActionPerformed( evt );
            }
        } );
        addButton.setText( "Add" );
        javax.swing.GroupLayout _addingNewBlocksTabLayout = new javax.swing.GroupLayout(
            _addingNewBlocksTab );
        _addingNewBlocksTab.setLayout( _addingNewBlocksTabLayout );
        _addingNewBlocksTabLayout
                .setHorizontalGroup( _addingNewBlocksTabLayout
                        .createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup(
                            _addingNewBlocksTabLayout
                                    .createSequentialGroup()
                                    .addGroup(
                                        _addingNewBlocksTabLayout
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING )
                                                .addGroup(
                                                    _addingNewBlocksTabLayout
                                                            .createSequentialGroup()
                                                            .addGap( 10, 10, 10 )
                                                            .addGroup(
                                                                _addingNewBlocksTabLayout
                                                                        .createParallelGroup(
                                                                            javax.swing.GroupLayout.Alignment.LEADING )
                                                                        .addComponent(
                                                                            _materialComboBox,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                        .addGroup(
                                                                            _addingNewBlocksTabLayout
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _zSizeLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _zSizeTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            _addingNewBlocksTabLayout
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _ySizeLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _ySizeTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            _addingNewBlocksTabLayout
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _xSizeLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _xSizeTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addComponent(
                                                                            _blockSizeLabel )
                                                                        .addGroup(
                                                                            _addingNewBlocksTabLayout
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _zCoordinateLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _zCoordinateTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            _addingNewBlocksTabLayout
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _yCoordinateLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _yCoordinateTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            _addingNewBlocksTabLayout
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _xCoordinateLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _xCoordinateTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addComponent(
                                                                            _blockCoordinatesLabel )
                                                                        .addComponent(
                                                                            _materialLabel )
                                                                        .addComponent(
                                                                            _newBlockLabel ) ) )
                                                .addGroup(
                                                    _addingNewBlocksTabLayout
                                                            .createSequentialGroup()
                                                            .addContainerGap().addComponent(
                                                                addButton ) ) ).addContainerGap(
                                        33, Short.MAX_VALUE ) ) );
        _addingNewBlocksTabLayout.setVerticalGroup( _addingNewBlocksTabLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            _addingNewBlocksTabLayout.createSequentialGroup().addGap( 16, 16, 16 ).addComponent(
                _newBlockLabel ).addGap( 18, 18, 18 ).addComponent( _materialLabel ).addGap( 9, 9,
                9 ).addComponent( _materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
                    .addComponent( _blockCoordinatesLabel ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        _addingNewBlocksTabLayout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.BASELINE ).addComponent(
                            _xCoordinateLabel ).addComponent( _xCoordinateTextField,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        _addingNewBlocksTabLayout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.BASELINE ).addComponent(
                            _yCoordinateLabel ).addComponent( _yCoordinateTextField,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        _addingNewBlocksTabLayout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.LEADING ).addComponent(
                            _zCoordinateLabel ).addComponent( _zCoordinateTextField,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED ).addComponent(
                        _blockSizeLabel ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        _addingNewBlocksTabLayout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( _xSizeLabel )
                                .addComponent( _xSizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        _addingNewBlocksTabLayout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( _ySizeLabel )
                                .addComponent( _ySizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        _addingNewBlocksTabLayout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.LEADING ).addComponent( _zSizeLabel )
                                .addComponent( _zSizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18, 18, 18 )
                    .addComponent( addButton ).addContainerGap( 208, Short.MAX_VALUE ) ) );
        _menuPanel.addTab( "Adding new blocks", _addingNewBlocksTab );
        _helpTextArea.setColumns( 20 );
        _helpTextArea.setFont( new java.awt.Font( "Monospaced", 0, 12 ) );
        _helpTextArea.setLineWrap( true );
        _helpTextArea.setRows( 5 );
        _helpTextArea.setText( "Opis jak uzywaæ edytor tekstowy i inne pierdo³ki...." );
        _helpTextArea.setAutoscrolls( false );
        jScrollPane1.setViewportView( _helpTextArea );
        javax.swing.GroupLayout _helpTabLayout = new javax.swing.GroupLayout( _helpTab );
        _helpTab.setLayout( _helpTabLayout );
        _helpTabLayout.setHorizontalGroup( _helpTabLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            _helpTabLayout.createSequentialGroup().addContainerGap()
                    .addComponent( jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222,
                        javax.swing.GroupLayout.PREFERRED_SIZE ).addContainerGap(
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) ) );
        _helpTabLayout.setVerticalGroup( _helpTabLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            _helpTabLayout.createSequentialGroup().addGap( 26, 26, 26 )
                    .addComponent( jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                        javax.swing.GroupLayout.PREFERRED_SIZE ).addContainerGap( 305,
                        Short.MAX_VALUE ) ) );
        _menuPanel.addTab( "Help", _helpTab );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
        this.setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addContainerGap().addComponent( _menuPanel,
                javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE ).addContainerGap() ) );
        layout.setVerticalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addComponent( _menuPanel,
                javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE ).addContainerGap() ) );
    }// </editor-fold>

    private void _xSizeTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _ySizeTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _zSizeTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _zCoordinateTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _yCoordinateTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _xCoordinateTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
    }

    private void _materialComboBoxActionPerformed( java.awt.event.ActionEvent evt )
    {
        System.out.println( "material chosen" );
    }

    private void _simulationStartButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _simulationStopButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _simulationPauseButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _simulationContinueButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _simulationRestartButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel _addingNewBlocksTab;
    private javax.swing.JLabel _blockCoordinatesLabel;
    private javax.swing.JLabel _blockSizeLabel;
    private javax.swing.JPanel _helpTab;
    private javax.swing.JTextArea _helpTextArea;
    private javax.swing.JComboBox _materialComboBox;
    private javax.swing.JLabel _materialLabel;
    private javax.swing.JTabbedPane _menuPanel;
    private javax.swing.JLabel _newBlockLabel;
    private javax.swing.JButton _simulationContinueButton;
    private javax.swing.JButton _simulationPauseButton;
    private javax.swing.JButton _simulationRestartButton;
    private javax.swing.JButton _simulationStartButton;
    private javax.swing.JButton _simulationStopButton;
    private javax.swing.JPanel _simulationTab;
    private javax.swing.JLabel _xCoordinateLabel;
    private javax.swing.JTextField _xCoordinateTextField;
    private javax.swing.JLabel _xSizeLabel;
    private javax.swing.JTextField _xSizeTextField;
    private javax.swing.JLabel _yCoordinateLabel;
    private javax.swing.JTextField _yCoordinateTextField;
    private javax.swing.JLabel _ySizeLabel;
    private javax.swing.JTextField _ySizeTextField;
    private javax.swing.JLabel _zCoordinateLabel;
    private javax.swing.JTextField _zCoordinateTextField;
    private javax.swing.JLabel _zSizeLabel;
    private javax.swing.JTextField _zSizeTextField;
    private javax.swing.JToggleButton addButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane6;
    // End of variables declaration
    private String _materialName = "Wood";
    private double _xCoordinate;
    private double _yCoordinate;
    private double _zCoordinate;
    private double _xSize;
    private double _ySize;
    private double _zSize;
    Scene3D _editedScene;
}
