/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * MenuPanel.java
 *
 * Created on 2010-11-14, 09:00:11
 */
package Interface;

/**
 * 
 * @author Dorota
 */
public class MenuPanel extends javax.swing.JPanel
{
    /** Creates new form MenuPanel */
    public MenuPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {
        _materialLabel = new javax.swing.JLabel();
        _newBlockLabel = new javax.swing.JLabel();
        _materialComboBox = new javax.swing.JComboBox();
        _blockCoordinatesLabel = new javax.swing.JLabel();
        _xCoordinateLabel = new javax.swing.JLabel();
        _yCoordinateLabel = new javax.swing.JLabel();
        _zCoordinateLabel = new javax.swing.JLabel();
        _xCoordinateTextField = new javax.swing.JTextField();
        _yCoordinateTextField = new javax.swing.JTextField();
        _zCoordinateTextField = new javax.swing.JTextField();
        _blockSizeLabel = new javax.swing.JLabel();
        _zSizeLabel = new javax.swing.JLabel();
        _zSizeTextField = new javax.swing.JTextField();
        _ySizeLabel = new javax.swing.JLabel();
        _ySizeTextField = new javax.swing.JTextField();
        _xSizeLabel = new javax.swing.JLabel();
        _xSizeTextField = new javax.swing.JTextField();
        _materialLabel.setText( "Material:" );
        _newBlockLabel.setText( "Add new block:" );
        _materialComboBox.setModel( new javax.swing.DefaultComboBoxModel( new String[]{ "Wood",
                "Air", "Metal", "Brick" } ) );
        _blockCoordinatesLabel.setText( "Block left-front-bottom coordinates:" );
        _xCoordinateLabel.setText( "x:" );
        _yCoordinateLabel.setText( "y:" );
        _zCoordinateLabel.setText( "z:" );
        _blockSizeLabel.setText( "Block size:" );
        _zSizeLabel.setText( "z:" );
        _ySizeLabel.setText( "y:" );
        _xSizeLabel.setText( "x:" );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
        this.setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addGap( 10, 10, 10 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addComponent( _materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE ).addGroup(
                            layout.createSequentialGroup().addComponent( _zSizeLabel )
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                    .addComponent( _zSizeTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGroup(
                            layout.createSequentialGroup().addComponent( _ySizeLabel )
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                    .addComponent( _ySizeTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGroup(
                            layout.createSequentialGroup().addComponent( _xSizeLabel )
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                    .addComponent( _xSizeTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE ) ).addComponent(
                            _blockSizeLabel ).addGroup(
                            layout.createSequentialGroup().addComponent( _zCoordinateLabel )
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                    .addComponent( _zCoordinateTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGroup(
                            layout.createSequentialGroup().addComponent( _yCoordinateLabel )
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                    .addComponent( _yCoordinateTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGroup(
                            layout.createSequentialGroup().addComponent( _xCoordinateLabel )
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                    .addComponent( _xCoordinateTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE ) ).addComponent(
                            _blockCoordinatesLabel ).addComponent( _materialLabel ).addComponent(
                            _newBlockLabel ) ).addContainerGap( 32, Short.MAX_VALUE ) ) );
        layout.setVerticalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addGap( 16, 16, 16 ).addComponent( _newBlockLabel )
                    .addGap( 18, 18, 18 ).addComponent( _materialLabel ).addGap( 9, 9, 9 )
                    .addComponent( _materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED ).addComponent(
                        _blockCoordinatesLabel ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _xCoordinateLabel ).addComponent(
                                    _xCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _yCoordinateLabel ).addComponent(
                                    _yCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( _zCoordinateLabel ).addComponent(
                                    _zCoordinateTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED ).addComponent(
                        _blockSizeLabel ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _xSizeLabel ).addComponent( _xSizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _ySizeLabel ).addComponent( _ySizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( _zSizeLabel ).addComponent( _zSizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addContainerGap( 46,
                        Short.MAX_VALUE ) ) );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel _blockCoordinatesLabel;
    private javax.swing.JLabel _blockSizeLabel;
    private javax.swing.JComboBox _materialComboBox;
    private javax.swing.JLabel _materialLabel;
    private javax.swing.JLabel _newBlockLabel;
    private javax.swing.JLabel _xCoordinateLabel;
    private javax.swing.JTextField _xCoordinateTextField;
    private javax.swing.JLabel _xSizeLabel;
    private javax.swing.JTextField _xSizeTextField;
    private javax.swing.JLabel _yCoordinateLabel;
    private javax.swing.JTextField _yCoordinateTextField;
    private javax.swing.JLabel _ySizeLabel;
    private javax.swing.JTextField _ySizeTextField;
    private javax.swing.JLabel _zCoordinateLabel;
    private javax.swing.JTextField _zCoordinateTextField;
    private javax.swing.JLabel _zSizeLabel;
    private javax.swing.JTextField _zSizeTextField;
    // End of variables declaration
}
