package Controller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.vecmath.Point3d;

import Model.World;
import View.Scene3D;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * MenuPanel.java
 *
 * Created on 2010-11-27, 10:44:40
 */
/**
 * 
 * @author Dorota
 */
public class MenuPanel extends javax.swing.JPanel
{
    /** Creates new form MenuPanel */
    public MenuPanel( Scene3D scene )
    {
        _editedScene = scene;
        _world = World.getWorld( scene );
        sMgr = new SimulationMgr( _world );
        // createTitle
        // setBackgroundColor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        _menuPanel = new javax.swing.JTabbedPane();
        _addingNewBlocksTab = new javax.swing.JPanel();
        _materialLabel = new javax.swing.JLabel();
        _newBlockLabel = new javax.swing.JLabel();
        _materialComboBox = new javax.swing.JComboBox();
        _blockCoordinatesLabel = new javax.swing.JLabel();
        _xCoordinateLabel = new javax.swing.JLabel();
        _yCoordinateLabel = new javax.swing.JLabel();
        _zCoordinateLabel = new javax.swing.JLabel();
        _xCoordinateTextField = new javax.swing.JTextField();
        _yCoordinateTextField = new javax.swing.JTextField();
        _zCoordinateTextField = new javax.swing.JTextField();
        _blockSizeLabel = new javax.swing.JLabel();
        _zSizeLabel = new javax.swing.JLabel();
        _zSizeTextField = new javax.swing.JTextField();
        _ySizeLabel = new javax.swing.JLabel();
        _ySizeTextField = new javax.swing.JTextField();
        _xSizeLabel = new javax.swing.JLabel();
        _xSizeTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JToggleButton();
        _helpTab = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout( jPanel1 );
        jPanel1.setLayout( gl_jPanel1 );
        gl_jPanel1.setHorizontalGroup( gl_jPanel1.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        gl_jPanel1.setVerticalGroup( gl_jPanel1.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        javax.swing.GroupLayout gl_jPanel2 = new javax.swing.GroupLayout( jPanel2 );
        jPanel2.setLayout( gl_jPanel2 );
        gl_jPanel2.setHorizontalGroup( gl_jPanel2.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        gl_jPanel2.setVerticalGroup( gl_jPanel2.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        javax.swing.GroupLayout gl_jPanel3 = new javax.swing.GroupLayout( jPanel3 );
        jPanel3.setLayout( gl_jPanel3 );
        gl_jPanel3.setHorizontalGroup( gl_jPanel3.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        gl_jPanel3.setVerticalGroup( gl_jPanel3.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 100, Short.MAX_VALUE ) );
        _materialLabel.setText( "Material:" );
        _newBlockLabel.setText( "Add new block:" );
        _materialComboBox.setModel( new javax.swing.DefaultComboBoxModel( new String[]{ "Wood",
                "Air", "Metal", "Brick" } ) );
        _materialComboBox.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _materialComboBoxActionPerformed( evt );
            }
        } );
        _blockCoordinatesLabel.setText( "Block left-front-bottom coordinates:" );
        _xCoordinateLabel.setText( "x:" );
        _yCoordinateLabel.setText( "y:" );
        _zCoordinateLabel.setText( "z:" );
        _xCoordinateTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _xCoordinateTextFieldActionPerformed( evt );
            }
        } );
        _yCoordinateTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _yCoordinateTextFieldActionPerformed( evt );
            }
        } );
        _zCoordinateTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _zCoordinateTextFieldActionPerformed( evt );
            }
        } );
        _blockSizeLabel.setText( "Block size:" );
        _zSizeLabel.setText( "z:" );
        _zSizeTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _zSizeTextFieldActionPerformed( evt );
            }
        } );
        _ySizeLabel.setText( "y:" );
        _ySizeTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _ySizeTextFieldActionPerformed( evt );
            }
        } );
        _xSizeLabel.setText( "x:" );
        _xSizeTextField.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _xSizeTextFieldActionPerformed( evt );
            }
        } );
        addButton.setText( "Add" );
        addButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _addButtonActionPerformed( evt );
            }
        } );
        javax.swing.GroupLayout gl__addingNewBlocksTab = new javax.swing.GroupLayout(
            _addingNewBlocksTab );
        _addingNewBlocksTab.setLayout( gl__addingNewBlocksTab );
        gl__addingNewBlocksTab
                .setHorizontalGroup( gl__addingNewBlocksTab
                        .createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup(
                            gl__addingNewBlocksTab
                                    .createSequentialGroup()
                                    .addGroup(
                                        gl__addingNewBlocksTab
                                                .createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING )
                                                .addGroup(
                                                    gl__addingNewBlocksTab
                                                            .createSequentialGroup()
                                                            .addGap( 10, 10, 10 )
                                                            .addGroup(
                                                                gl__addingNewBlocksTab
                                                                        .createParallelGroup(
                                                                            javax.swing.GroupLayout.Alignment.LEADING )
                                                                        .addComponent(
                                                                            _materialComboBox,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                        .addGroup(
                                                                            gl__addingNewBlocksTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _zSizeLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _zSizeTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            gl__addingNewBlocksTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _ySizeLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _ySizeTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            gl__addingNewBlocksTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _xSizeLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _xSizeTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addComponent(
                                                                            _blockSizeLabel )
                                                                        .addGroup(
                                                                            gl__addingNewBlocksTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _zCoordinateLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _zCoordinateTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            gl__addingNewBlocksTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _yCoordinateLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _yCoordinateTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addGroup(
                                                                            gl__addingNewBlocksTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        _xCoordinateLabel )
                                                                                    .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                                    .addComponent(
                                                                                        _xCoordinateTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                                        .addComponent(
                                                                            _blockCoordinatesLabel )
                                                                        .addComponent(
                                                                            _materialLabel )
                                                                        .addComponent(
                                                                            _newBlockLabel ) ) )
                                                .addGroup(
                                                    gl__addingNewBlocksTab.createSequentialGroup()
                                                            .addContainerGap()
                                                            .addComponent( addButton ) ) )
                                    .addContainerGap( 17, Short.MAX_VALUE ) ) );
        gl__addingNewBlocksTab.setVerticalGroup( gl__addingNewBlocksTab.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            gl__addingNewBlocksTab
                    .createSequentialGroup()
                    .addGap( 16, 16, 16 )
                    .addComponent( _newBlockLabel )
                    .addGap( 18, 18, 18 )
                    .addComponent( _materialLabel )
                    .addGap( 9, 9, 9 )
                    .addComponent( _materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
                    .addComponent( _blockCoordinatesLabel )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                    .addGroup(
                        gl__addingNewBlocksTab
                                .createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _xCoordinateLabel )
                                .addComponent( _xCoordinateTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                    .addGroup(
                        gl__addingNewBlocksTab
                                .createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _yCoordinateLabel )
                                .addComponent( _yCoordinateTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                    .addGroup(
                        gl__addingNewBlocksTab
                                .createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( _zCoordinateLabel )
                                .addComponent( _zCoordinateTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
                    .addComponent( _blockSizeLabel )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                    .addGroup(
                        gl__addingNewBlocksTab
                                .createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _xSizeLabel )
                                .addComponent( _xSizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                    .addGroup(
                        gl__addingNewBlocksTab
                                .createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                .addComponent( _ySizeLabel )
                                .addComponent( _ySizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                    .addGroup(
                        gl__addingNewBlocksTab
                                .createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                .addComponent( _zSizeLabel )
                                .addComponent( _zSizeTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18, 18, 18 )
                    .addComponent( addButton ).addContainerGap( 208, Short.MAX_VALUE ) ) );
        _menuPanel.addTab( "Adding new blocks", _addingNewBlocksTab );
        jTextArea1.setColumns( 20 );
        jTextArea1.setFont( new java.awt.Font( "Calibri", 0, 13 ) );
        jTextArea1.setLineWrap( true );
        jTextArea1.setRows( 5 );
        jTextArea1
                .setText( "# - komentarz do koñca linii\n(x,y,z) - wspó³rzêdne punkt left-back-button\n[x,y,z] - wielkoœæ bloku\n\nJednostka: komórki CA wielkoœci:\n0.5m x 0.5m x 0.5m\n\nKa¿dy blok podajemy w osobnej linii, \nakceptuj¹c jego dodanie przyciskiem\nEnter.\n\nOpis bloku ma postaæ:\n(x,y,z) [x,y,z]: Materia³ , ... , ...\n\nObecnie dostêpne materia³y:\ndrewno\n\nPo materiale mo¿na bêdzie podaæ dodatkowe parametry w ustalonej kolejnoœci jak je dodam (dla nas wewnêtrzne jak kiedyœ bêd¹ potrzebne)." );
        jTextArea1.setAutoscrolls( false );
        jScrollPane1.setViewportView( jTextArea1 );
        javax.swing.GroupLayout gl_jPanel4 = new javax.swing.GroupLayout( jPanel4 );
        jPanel4.setLayout( gl_jPanel4 );
        gl_jPanel4.setHorizontalGroup( gl_jPanel4.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addComponent( jScrollPane1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE ) );
        gl_jPanel4.setVerticalGroup( gl_jPanel4.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addComponent( jScrollPane1,
            javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550,
            Short.MAX_VALUE ) );
        jTabbedPane1.addTab( "Editor", jPanel4 );
        javax.swing.GroupLayout gl__helpTab = new javax.swing.GroupLayout( _helpTab );
        _helpTab.setLayout( gl__helpTab );
        gl__helpTab.setHorizontalGroup( gl__helpTab.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addComponent( jTabbedPane1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE ) );
        gl__helpTab.setVerticalGroup( gl__helpTab.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addComponent( jTabbedPane1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE ) );
        _menuPanel.addTab( "Help", _helpTab );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
        this.setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent( _menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 235,
                        Short.MAX_VALUE ).addContainerGap() ) );
        layout.setVerticalGroup( layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup()
                    .addComponent( _menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 610,
                        Short.MAX_VALUE ).addContainerGap() ) );
        _simulationTab = new javax.swing.JPanel();
        _simulationStopButton = new javax.swing.JButton();
        _simulationRestartButton = new javax.swing.JButton();
        _simulationContinueButton = new javax.swing.JButton();
        _simulationPauseButton = new javax.swing.JButton();
        _simulationStartButton = new javax.swing.JButton();
        _simulationStopButton.setText( "Stop" );
        _simulationStopButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationStopButtonActionPerformed( evt );
            }
        } );
        _simulationRestartButton.setText( "Restart" );
        _simulationRestartButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationRestartButtonActionPerformed( evt );
            }
        } );
        _simulationContinueButton.setText( "Continue" );
        _simulationContinueButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationContinueButtonActionPerformed( evt );
            }
        } );
        _simulationPauseButton.setText( "Pause" );
        _simulationPauseButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationPauseButtonActionPerformed( evt );
            }
        } );
        _simulationStartButton.setText( "Start" );
        _simulationStartButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                _simulationStartButtonActionPerformed( evt );
            }
        } );
        JLabel fireInitLabel = new JLabel( "Fire start point" );
        lblX = new JLabel( "x:" );
        lblY = new JLabel( "y:" );
        lblZ = new JLabel( "z:" );
        _startFireXTextField = new JTextField();
        _startFireXTextField.addActionListener( new ActionListener()
        {
            public void actionPerformed( ActionEvent arg0 )
            {
                _startOfFireX = Integer.valueOf( _startFireXTextField.getText() );
            }
        } );
        _startFireXTextField.setToolTipText( "x coordinate" );
        _startFireXTextField.setColumns( 10 );
        _startFireTextFieldY = new JTextField();
        _startFireTextFieldY.addActionListener( new ActionListener()
        {
            public void actionPerformed( ActionEvent arg0 )
            {
                _startOfFireY = Integer.valueOf( _startFireTextFieldY.getText() );
            }
        } );
        _startFireTextFieldY.setToolTipText( "y coordinate" );
        _startFireTextFieldY.setColumns( 10 );
        _startFireTextFieldZ = new JTextField();
        _startFireTextFieldZ.addActionListener( new ActionListener()
        {
            public void actionPerformed( ActionEvent arg0 )
            {
                _startOfFireZ = Integer.valueOf( _startFireTextFieldZ.getText() );
            }
        } );
        _startFireTextFieldZ.setToolTipText( "z coordinate" );
        _startFireTextFieldZ.setColumns( 10 );
        javax.swing.GroupLayout gl__simulationTab = new javax.swing.GroupLayout( _simulationTab );
        gl__simulationTab
                .setHorizontalGroup( gl__simulationTab
                        .createParallelGroup( Alignment.LEADING )
                        .addGroup(
                            gl__simulationTab
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(
                                        gl__simulationTab
                                                .createParallelGroup( Alignment.LEADING )
                                                .addGroup(
                                                    gl__simulationTab.createSequentialGroup()
                                                            .addComponent( fireInitLabel )
                                                            .addContainerGap( 353, Short.MAX_VALUE ) )
                                                .addGroup(
                                                    gl__simulationTab
                                                            .createSequentialGroup()
                                                            .addGroup(
                                                                gl__simulationTab
                                                                        .createParallelGroup(
                                                                            Alignment.TRAILING,
                                                                            false )
                                                                        .addGroup(
                                                                            Alignment.LEADING,
                                                                            gl__simulationTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        lblZ )
                                                                                    .addPreferredGap(
                                                                                        ComponentPlacement.UNRELATED )
                                                                                    .addComponent(
                                                                                        _startFireTextFieldZ,
                                                                                        0,
                                                                                        0,
                                                                                        Short.MAX_VALUE ) )
                                                                        .addGroup(
                                                                            Alignment.LEADING,
                                                                            gl__simulationTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        lblY )
                                                                                    .addPreferredGap(
                                                                                        ComponentPlacement.UNRELATED )
                                                                                    .addComponent(
                                                                                        _startFireTextFieldY,
                                                                                        0,
                                                                                        0,
                                                                                        Short.MAX_VALUE ) )
                                                                        .addGroup(
                                                                            Alignment.LEADING,
                                                                            gl__simulationTab
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        lblX )
                                                                                    .addPreferredGap(
                                                                                        ComponentPlacement.UNRELATED )
                                                                                    .addComponent(
                                                                                        _startFireXTextField,
                                                                                        GroupLayout.PREFERRED_SIZE,
                                                                                        69,
                                                                                        GroupLayout.PREFERRED_SIZE ) ) )
                                                            .addContainerGap() )
                                                .addGroup(
                                                    gl__simulationTab
                                                            .createSequentialGroup()
                                                            .addComponent( _simulationStartButton,
                                                                GroupLayout.DEFAULT_SIZE, 226,
                                                                Short.MAX_VALUE ).addGap( 183 ) )
                                                .addGroup(
                                                    gl__simulationTab
                                                            .createSequentialGroup()
                                                            .addComponent( _simulationStopButton,
                                                                GroupLayout.DEFAULT_SIZE, 226,
                                                                Short.MAX_VALUE ).addGap( 183 ) )
                                                .addGroup(
                                                    gl__simulationTab
                                                            .createSequentialGroup()
                                                            .addComponent( _simulationPauseButton,
                                                                GroupLayout.DEFAULT_SIZE, 226,
                                                                Short.MAX_VALUE ).addGap( 183 ) )
                                                .addGroup(
                                                    gl__simulationTab
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                _simulationContinueButton,
                                                                GroupLayout.DEFAULT_SIZE, 226,
                                                                Short.MAX_VALUE ).addGap( 183 ) )
                                                .addGroup(
                                                    gl__simulationTab
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                _simulationRestartButton,
                                                                GroupLayout.DEFAULT_SIZE, 226,
                                                                Short.MAX_VALUE ).addGap( 183 ) ) ) ) );
        gl__simulationTab.setVerticalGroup( gl__simulationTab.createParallelGroup(
            Alignment.LEADING )
                .addGroup(
                    gl__simulationTab
                            .createSequentialGroup()
                            .addContainerGap()
                            .addComponent( fireInitLabel )
                            .addGap( 18 )
                            .addGroup(
                                gl__simulationTab
                                        .createParallelGroup( Alignment.BASELINE )
                                        .addComponent( lblX )
                                        .addComponent( _startFireXTextField,
                                            GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE ) )
                            .addGroup(
                                gl__simulationTab
                                        .createParallelGroup( Alignment.LEADING )
                                        .addGroup(
                                            gl__simulationTab.createSequentialGroup().addGap( 9 )
                                                    .addComponent( lblY )
                                                    .addPreferredGap( ComponentPlacement.UNRELATED )
                                                    .addComponent( lblZ ) )
                                        .addGroup(
                                            gl__simulationTab
                                                    .createSequentialGroup()
                                                    .addGap( 7 )
                                                    .addComponent( _startFireTextFieldY,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.PREFERRED_SIZE )
                                                    .addPreferredGap( ComponentPlacement.RELATED )
                                                    .addComponent( _startFireTextFieldZ,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.PREFERRED_SIZE ) ) )
                            .addGap( 34 ).addComponent( _simulationStartButton ).addGap( 18 )
                            .addComponent( _simulationStopButton )
                            .addPreferredGap( ComponentPlacement.UNRELATED )
                            .addComponent( _simulationPauseButton ).addGap( 18 )
                            .addComponent( _simulationContinueButton ).addGap( 18 )
                            .addComponent( _simulationRestartButton )
                            .addContainerGap( 99, Short.MAX_VALUE ) ) );
        _simulationTab.setLayout( gl__simulationTab );
        _menuPanel.addTab( "Simulation", _simulationTab );
    }// </editor-fold>

    private void _simulationStartButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        _world.setStartOfFire( _startOfFireX, _startOfFireY, _startOfFireZ );
        sMgr.manageSimulation();
    }

    private void _simulationStopButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _simulationPauseButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _simulationContinueButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _simulationRestartButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        // TODO add your handling code here:
    }

    private void _materialComboBoxActionPerformed( java.awt.event.ActionEvent evt )
    {
        _materialName = _materialComboBox.getSelectedItem().toString();
    }

    private void _xCoordinateTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        _xCoordinate = Integer.parseInt( _xCoordinateTextField.getText() );
    }

    private void _yCoordinateTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        _yCoordinate = Integer.parseInt( _yCoordinateTextField.getText() );
    }

    private void _zCoordinateTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        _zCoordinate = Integer.parseInt( _zCoordinateTextField.getText() );
    }

    private void _xSizeTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        _xSize = Integer.parseInt( _xSizeTextField.getText() );
    }

    private void _ySizeTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        _ySize = Integer.parseInt( _ySizeTextField.getText() );
    }

    private void _zSizeTextFieldActionPerformed( java.awt.event.ActionEvent evt )
    {
        _zSize = Integer.parseInt( _zSizeTextField.getText() );
    }

    private void _addButtonActionPerformed( java.awt.event.ActionEvent evt )
    {
        _world.addBuildingPart( new Point3d( _xCoordinate, _yCoordinate, _zCoordinate ),
            new Point3d( _xSize, _ySize, _zSize ), _materialName, _editedScene );
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel _addingNewBlocksTab;
    private javax.swing.JLabel _blockCoordinatesLabel;
    private javax.swing.JLabel _blockSizeLabel;
    private javax.swing.JPanel _helpTab;
    private javax.swing.JComboBox _materialComboBox;
    private javax.swing.JLabel _materialLabel;
    private javax.swing.JTabbedPane _menuPanel;
    private javax.swing.JLabel _newBlockLabel;
    private javax.swing.JButton _simulationContinueButton;
    private javax.swing.JButton _simulationPauseButton;
    private javax.swing.JButton _simulationRestartButton;
    private javax.swing.JButton _simulationStartButton;
    private javax.swing.JButton _simulationStopButton;
    private javax.swing.JPanel _simulationTab;
    private javax.swing.JLabel _xCoordinateLabel;
    private javax.swing.JTextField _xCoordinateTextField;
    private javax.swing.JLabel _xSizeLabel;
    private javax.swing.JTextField _xSizeTextField;
    private javax.swing.JLabel _yCoordinateLabel;
    private javax.swing.JTextField _yCoordinateTextField;
    private javax.swing.JLabel _ySizeLabel;
    private javax.swing.JTextField _ySizeTextField;
    private javax.swing.JLabel _zCoordinateLabel;
    private javax.swing.JTextField _zCoordinateTextField;
    private javax.swing.JLabel _zSizeLabel;
    private javax.swing.JTextField _zSizeTextField;
    private javax.swing.JToggleButton addButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration
    private String _materialName = "Wood";
    private double _xCoordinate;
    private double _yCoordinate;
    private double _zCoordinate;
    private double _xSize;
    private double _ySize;
    private double _zSize;
    Scene3D _editedScene;
    World _world;
    private JLabel lblX;
    private JLabel lblY;
    private JLabel lblZ;
    private JTextField _startFireXTextField;
    private JTextField _startFireTextFieldY;
    private JTextField _startFireTextFieldZ;
    private int _startOfFireX;
    private int _startOfFireY;
    private int _startOfFireZ;
    private SimulationMgr sMgr;
}
